In [1]:
import torch

VOCAB_SIZE= 20000
D_MODEL = 512
H = 8

## Embedding Testing

In [4]:
from Layers.Embeddings import EmbeddingBlock

embedding_layer = EmbeddingBlock(20000, 16)
test_input = torch.randint(1, 20000, (1,4))
print("Test input is tokens of: ", test_input, test_input.shape)
print(embedding_layer(test_input))
print(embedding_layer(test_input).shape)

Test input is tokens of:  tensor([[ 2628,  7036,  4506, 14908]]) torch.Size([1, 4])
tensor([[[-4.5036e+00, -5.5672e+00, -4.1392e+00, -3.2941e+00,  5.9770e+00,
          -4.5389e+00, -5.3009e+00, -4.2005e+00,  1.4870e+00, -5.9115e+00,
          -5.0675e+00, -5.2221e+00, -3.3135e+00,  1.9641e+00,  4.5450e+00,
           1.6506e+00],
         [ 5.2301e+00, -2.5679e+00,  5.2352e+00,  1.2096e+00,  6.1745e-01,
           4.9657e-01,  9.1401e+00,  7.6274e+00, -6.0109e-01, -4.2874e+00,
           5.0812e+00, -1.3623e+00,  3.1592e+00, -3.6923e-03, -3.1643e+00,
          -5.4966e+00],
         [ 2.6994e+00,  1.9002e+00, -2.9106e+00,  4.8400e+00, -7.0398e+00,
          -2.3991e+00, -6.3400e+00, -1.8030e+00,  3.9123e+00,  5.5260e+00,
          -2.5098e+00, -9.3217e+00,  3.9868e+00, -5.3261e+00, -1.0724e+00,
           3.7140e+00],
         [ 3.1381e+00,  2.7488e+00, -8.2415e-01,  3.1818e+00, -4.9028e+00,
          -5.1223e+00,  7.4400e-01,  3.2724e+00, -1.1744e-01,  2.6997e+00,
          -9.4989e+

## Positional Encoding Testing

In [5]:
from Layers.PositionalEncoding import PositionalEncoding

positional_encoding = PositionalEncoding(4, 16 ,0.25)
test_input = torch.rand((1, 4, 16))
print(positional_encoding(test_input))
print(positional_encoding(test_input).shape)

tensor([[[ 1.1295,  1.9298,  0.5414,  0.0000,  0.0000,  0.0000,  0.6256,
           1.6718,  0.5157,  1.3690,  0.4519,  0.0000,  0.8012,  2.6359,
           0.0000,  2.4429],
         [ 2.2259,  1.4177,  1.5458,  2.0607,  0.5226,  0.0000,  0.0000,
           1.5924,  1.0347,  2.4701,  0.0356,  2.1778,  1.2035,  1.5963,
           0.0000,  0.0000],
         [ 1.9492,  0.0000,  1.9600,  2.2534,  1.2347,  1.5421,  0.9355,
           1.6125,  0.9139,  0.0000,  0.8710,  1.9462,  0.5884,  1.8681,
           1.0019,  2.4022],
         [ 0.6053, -0.1528,  0.0000,  1.0149,  0.5343,  2.3441,  0.8776,
           1.8438,  0.6488,  1.6188,  0.0000,  1.8470,  0.0140,  2.5283,
           0.0000,  2.0420]]])
torch.Size([1, 4, 16])


## Multi Head Attention Testing

In [6]:
from Layers.MultiheadAttention import MultiHeadAttention

attention_layer = MultiHeadAttention(D_MODEL, H)
test_input = torch.rand((2, 3, D_MODEL))
print(attention_layer(test_input))
print(attention_layer(test_input).shape)

tensor([[[-0.2040,  0.0487,  0.2436,  ..., -0.0390, -0.4170, -0.1158],
         [-0.2035,  0.0497,  0.2409,  ..., -0.0368, -0.4178, -0.1148],
         [-0.2061,  0.0483,  0.2427,  ..., -0.0404, -0.4201, -0.1156]],

        [[-0.2290, -0.0286,  0.3884,  ..., -0.0559, -0.4017, -0.2037],
         [-0.2286, -0.0294,  0.3909,  ..., -0.0565, -0.4017, -0.2059],
         [-0.2275, -0.0302,  0.3910,  ..., -0.0571, -0.4024, -0.2047]]],
       grad_fn=<UnsafeViewBackward0>)
torch.Size([2, 3, 512])


## Add & Norm

In [7]:
from Layers.LayerNorm import LayerNorm

norm_layer = LayerNorm()
test_input = torch.rand((2, 3, D_MODEL))
norm_layer(test_input)

torch.Size([2, 3, 512])


tensor([[[ 0.4782, -0.6177, -0.2767,  ...,  1.1730, -1.7716,  1.1750],
         [ 0.5057,  0.7222, -0.9680,  ...,  0.6623,  1.2391,  1.2656],
         [-1.2151, -0.8058, -1.3872,  ..., -0.6932,  0.9948,  0.7757]],

        [[ 0.3453,  0.3215, -1.6191,  ...,  0.5086, -1.6324,  1.4238],
         [ 1.3010,  0.5088, -1.1941,  ..., -0.9013,  1.6259,  0.5029],
         [ 1.5469,  1.4449,  1.5605,  ...,  0.2131, -0.4877, -1.0547]]])

## Feed Forward

In [8]:
from Layers.FeedForward import FeedForward

feedforward = FeedForward(D_MODEL)
test_input = torch.rand((2, 3, D_MODEL))
feedforward(test_input)
feedforward(test_input).shape

torch.Size([2, 3, 512])

## Encoder Block

In [4]:
from Encoder import EncoderBlock

encoder_block = EncoderBlock(D_MODEL, H)

test_sequence = torch.rand((2, 3, D_MODEL))
print(encoder_block(test_sequence))
encoder_block(test_sequence).shape

tensor([[[ 0.3615,  0.4269, -1.0699,  ...,  1.9125, -0.1291,  1.5448],
         [-0.0362, -0.4151, -0.8038,  ...,  0.3672, -0.5678, -0.1476],
         [ 0.1215, -0.3947,  0.6951,  ...,  0.0058, -0.1143,  0.5160]],

        [[ 0.9706, -0.6031,  1.2964,  ...,  0.8685, -0.5434,  0.3184],
         [ 0.6125,  0.2766, -1.5923,  ...,  1.6767, -0.4318, -0.2972],
         [ 0.8932, -0.3232, -1.4655,  ...,  1.6698,  1.9464,  1.2935]]],
       grad_fn=<DivBackward0>)


torch.Size([2, 3, 512])