In [1]:
import torch
import numpy as np
np.set_printoptions(precision=4, suppress=True)

VOCAB_SIZE= 20000
D_MODEL = 512
H = 8

## Tokenizer Testing

## Embedding Testing

In [2]:
from Layers.Embeddings import EmbeddingBlock

embedding_layer = EmbeddingBlock(20000, 16)
test_input = torch.randint(1, 20000, (1,4))
print("Test input is tokens of: ", test_input, test_input.shape)
print(embedding_layer(test_input))
print(embedding_layer(test_input).shape)

Test input is tokens of:  tensor([[ 8144,  1910,  4745, 15998]]) torch.Size([1, 4])
tensor([[[ 2.5273, -0.4442,  0.1394, -2.8430,  0.4696, -1.2475, -3.1813,
           3.3183, -4.4957,  5.4773, -0.4740, -2.6666, -3.7937, -2.4665,
          -0.9539,  3.7215],
         [-7.4268,  2.0315, -2.0688, -5.7789, -1.3605,  3.7247, -4.8814,
          -2.7041,  6.1911, -2.5799, -0.3952,  5.3517, -4.1462, -0.8693,
           1.1422, -2.3019],
         [ 5.4945,  3.4861,  1.7259, -2.5638,  6.3585,  5.8787,  7.6610,
           3.1191,  2.0096, -7.2187, -6.5905, -1.8071, -7.8510,  7.6360,
           1.6610,  5.8790],
         [ 1.2579, -4.3629, -0.9344,  2.0162, -3.4799, -1.1254,  0.2272,
          -5.4324, -4.0819,  4.8355,  5.8816, -1.5671, -7.1820, -2.1454,
           6.5317, -2.3541]]], grad_fn=<MulBackward0>)
torch.Size([1, 4, 16])


## Positional Encoding Testing

In [3]:
from Layers.PositionalEncoding import PositionalEncoding

positional_encoding = PositionalEncoding(4, 16 ,0.25)
test_input = torch.rand((1, 4, 16))
print(positional_encoding(test_input))
print(positional_encoding(test_input).shape)

tensor([[[ 0.0000,  1.3639,  0.0000,  2.4305,  0.5409,  1.4384,  0.0223,
           1.3553,  0.8944,  2.1616,  0.0000,  0.0000,  0.0000,  1.7075,
           0.9829,  1.6339],
         [ 1.3623,  1.5771,  0.0000,  1.2691,  0.2823,  2.0313,  0.9972,
           2.3539,  0.2657,  0.0000,  0.5582,  2.1497,  1.2092,  2.2341,
           0.5669,  0.0000],
         [ 1.6035,  0.3378,  0.0000,  0.0000,  0.5822,  2.4379,  0.9184,
           1.4841,  1.2522,  1.5991,  0.0000,  2.0849,  0.0000,  0.0000,
           1.0255,  0.0000],
         [ 0.3651, -0.3724,  1.2539,  0.0000,  0.7610,  1.9501,  1.2415,
           1.9396,  0.3889,  2.2288,  0.0000,  1.8135,  0.8446,  2.4720,
           0.1835,  2.0190]]])
torch.Size([1, 4, 16])


## Multi Head Attention Testing

In [4]:
from Layers.MultiheadAttention import MultiHeadAttention

attention_layer = MultiHeadAttention(D_MODEL, H)
test_input = torch.rand((2, 3, D_MODEL))
# print(attention_layer(test_input))
print(attention_layer(test_input, test_input, test_input).shape)

torch.Size([2, 3, 512])


## Masked Multi Head Attention Testing

In [5]:
from Layers.MultiheadAttention import MultiHeadAttention

d_model = 4
attention_layer = MultiHeadAttention(d_model, 2)
test_input = torch.rand((2, 3, d_model))

mask = torch.tril(torch.full((3, 3), float('-inf')), diagonal=1)
print(attention_layer(test_input, test_input, test_input, mask = mask).shape)
print(attention_layer(test_input,test_input, test_input, mask = mask))

torch.Size([2, 3, 4])
tensor([[[-0.2907, -0.0473,  0.1274, -0.1866],
         [-0.2330, -0.0364,  0.1045, -0.1742],
         [-0.2326, -0.0363,  0.1038, -0.1747]],

        [[-0.1941, -0.0325,  0.0901, -0.1453],
         [-0.2001, -0.0244,  0.0823, -0.1498],
         [-0.1998, -0.0247,  0.0829, -0.1506]]], grad_fn=<UnsafeViewBackward0>)


## Add & Norm

In [6]:
from Layers.LayerNorm import LayerNorm

norm_layer = LayerNorm()
test_input = torch.rand((2, 3, D_MODEL))
norm_layer(test_input)

tensor([[[ 1.0434,  0.8006,  1.6418,  ..., -1.6031, -1.6123,  0.9580],
         [-1.4315, -0.2826, -1.5066,  ..., -0.6978, -1.5527, -0.1153],
         [-1.2213,  1.4000,  1.3781,  ...,  0.1130, -1.5059, -0.1161]],

        [[ 1.4222,  1.3329,  0.8774,  ...,  1.5367,  0.6644, -0.0336],
         [ 1.5521,  0.5558, -1.0246,  ...,  0.4323,  0.6481,  0.2574],
         [ 0.9300, -1.3316, -0.9123,  ...,  0.1650,  0.0065,  1.6932]]])

## Feed Forward

In [7]:
from Layers.FeedForward import FeedForward

feedforward = FeedForward(D_MODEL)
test_input = torch.rand((2, 3, D_MODEL))
feedforward(test_input)
feedforward(test_input).shape

torch.Size([2, 3, 512])

## Encoder Block

In [10]:
from Encoder import EncoderBlock

encoder_block = EncoderBlock(D_MODEL, H)

test_sequence = torch.rand((2, 3, D_MODEL))
encoder_output = encoder_block(test_sequence)
print()
encoder_block(test_sequence).shape

torch.Size([2, 3, 512])

## Decoder Block

In [ ]:
from Decoder import DecoderBlock

decoder_block = DecoderBlock(D_MODEL, H)
test_sequence = torch.rand((2, 3, D_MODEL))

decoderـoutput = decoder_block(test_sequence, encoder_output, )

TypeError: DecoderBlock.forward() missing 2 required positional arguments: 'src_mask' and 'tgt_mask'

## Drafts