In [1]:
import torch
import numpy as np
np.set_printoptions(precision=4, suppress=True)

VOCAB_SIZE= 20000
D_MODEL = 512
H = 8

## Tokenizer Testing

## Embedding Testing

In [2]:
from Layers.Embeddings import EmbeddingBlock

embedding_layer = EmbeddingBlock(20000, 16)
test_input = torch.randint(1, 20000, (1,4))
print("Test input is tokens of: ", test_input, test_input.shape)
print(embedding_layer(test_input))
print(embedding_layer(test_input).shape)

Test input is tokens of:  tensor([[1505,  169, 2311, 2838]]) torch.Size([1, 4])
tensor([[[ 2.3094e+00,  1.2018e+00,  1.4039e+00, -3.5311e+00,  7.1234e-01,
          -1.4797e-02,  3.7777e+00, -7.0283e+00, -6.8552e+00,  4.2303e+00,
           2.0433e+00,  2.5598e+00, -1.2306e+01,  7.5334e+00, -6.6835e+00,
          -2.4895e-01],
         [ 5.9639e+00, -8.8417e+00,  6.2787e+00, -1.8326e+00, -4.9008e+00,
           2.1509e+00, -3.1909e-01, -3.5558e+00,  7.0075e+00, -6.1189e+00,
           1.7107e+00,  1.3032e+00, -4.8227e+00, -7.3234e-01, -2.2931e+00,
           3.7251e+00],
         [ 6.1912e+00, -3.2242e+00,  2.5643e+00, -2.5125e-01, -1.9621e+00,
          -6.7807e-01,  2.6701e+00,  2.3185e+00,  2.4377e+00, -3.3283e+00,
          -2.9812e+00, -1.2073e+00,  3.2733e+00, -5.2563e+00, -5.2393e+00,
           3.7234e-01],
         [ 5.8693e+00,  4.6047e+00, -1.2913e+00, -7.7520e-01, -5.7460e+00,
           8.1350e-02,  3.1981e+00,  4.0445e+00, -5.2387e+00, -1.6050e+01,
           9.3568e+00, 

## Positional Encoding Testing

In [3]:
from Layers.PositionalEncoding import PositionalEncoding

positional_encoding = PositionalEncoding(4, 16 ,0.25)
test_input = torch.rand((1, 4, 16))
print(positional_encoding(test_input))
print(positional_encoding(test_input).shape)

tensor([[[ 0.0000,  0.0000,  0.0200,  0.0000,  1.3027,  0.0000,  1.1090,
           1.4993,  0.9913,  1.7732,  0.0000,  1.8115,  0.3397,  2.5990,
           1.0511,  2.5766],
         [ 2.0984,  2.0038,  0.8554,  0.0000,  0.4960,  0.0000,  0.0614,
           1.6073,  0.9918,  1.7931,  0.0000,  2.5771,  0.6317,  1.5380,
           0.0000,  2.6391],
         [ 0.0000,  0.1336,  2.0375,  2.3566,  0.7821,  2.4963,  0.3940,
           2.2207,  0.4048,  2.2217,  0.2199,  2.3403,  0.0000,  1.5762,
           1.1057,  1.8906],
         [ 0.0000, -0.4886,  2.1734,  0.0000,  1.5345,  2.3526,  0.0000,
           1.3780,  1.2266,  2.5526,  0.4681,  1.4926,  0.1675,  1.3441,
           0.0000,  0.0000]]])
torch.Size([1, 4, 16])


## Multi Head Attention Testing

In [4]:
from Layers.MultiheadAttention import MultiHeadAttention

attention_layer = MultiHeadAttention(D_MODEL, H)
test_input = torch.rand((2, 3, D_MODEL))
# print(attention_layer(test_input))
print(attention_layer(test_input, test_input, test_input).shape)

torch.Size([2, 3, 512])


## Masked Multi Head Attention Testing

In [5]:
from Layers.MultiheadAttention import MultiHeadAttention

d_model = 4
attention_layer = MultiHeadAttention(d_model, 2)
test_input = torch.rand((2, 3, d_model))

mask = torch.tril(torch.full((3, 3), float('-inf')), diagonal=1)
print(attention_layer(test_input, test_input, test_input, mask = mask).shape)
print(attention_layer(test_input,test_input, test_input, mask = mask))

torch.Size([2, 3, 4])
tensor([[[-0.2575, -0.2138,  0.0468, -0.0036],
         [-0.2988, -0.2617,  0.0504, -0.0158],
         [-0.2987, -0.2617,  0.0504, -0.0158]],

        [[-0.0738, -0.1595, -0.0668, -0.1613],
         [-0.0613, -0.1362, -0.0752, -0.1491],
         [-0.0589, -0.1368, -0.0770, -0.1547]]], grad_fn=<UnsafeViewBackward0>)


## Add & Norm

In [6]:
from Layers.LayerNorm import LayerNorm

norm_layer = LayerNorm()
test_input = torch.rand((2, 3, D_MODEL))
norm_layer(test_input)

tensor([[[ 0.3645, -1.6176,  0.4524,  ...,  0.1975,  0.3822,  0.9038],
         [ 1.3095,  1.4172, -1.1247,  ...,  1.5721,  1.7984,  1.5626],
         [-1.2415, -0.4929, -0.7654,  ..., -1.0214, -0.9954,  0.7572]],

        [[-1.3115, -0.4174,  1.4512,  ...,  0.4677,  0.9365,  0.0890],
         [-0.9452,  1.3777,  0.5976,  ...,  0.5552, -1.2069, -1.2767],
         [ 0.2591,  0.2075, -0.5823,  ...,  0.4914,  1.2929,  0.0921]]])

## Feed Forward

In [7]:
from Layers.FeedForward import FeedForward

feedforward = FeedForward(D_MODEL)
test_input = torch.rand((2, 3, D_MODEL))
feedforward(test_input)
feedforward(test_input).shape

torch.Size([2, 3, 512])

## Encoder Block

In [8]:
from Encoder import EncoderBlock

encoder_block = EncoderBlock(D_MODEL, H)

test_sequence = torch.rand((2, 3, D_MODEL))
encoder_output = encoder_block(test_sequence)
encoder_block(test_sequence).shape

TypeError: EncoderBlock.forward() missing 1 required positional argument: 'src_mask'

## Decoder Block + Full flow test

In [21]:
import torch.nn as nn 

from Layers.Embeddings import EmbeddingBlock
from Layers.PositionalEncoding import PositionalEncoding

from Encoder import EncoderBlock
from Decoder import DecoderBlock

max_src_len = 7
max_tgt_len = 9

input_tokens = torch.Tensor([[382, 747, 472, 472, 72]]).to(torch.long)
input_tokens = nn.functional.pad(input_tokens, (0,max_src_len - input_tokens.shape[1]), mode='constant', value=1)

src_masking = input_tokens != 1
## Mask shape must be (b_size, heads, seq_len, seq_len) to be able to broadcast so (b_size, 1, 1, seq_len)
src_masking = src_masking.unsqueeze(1).unsqueeze(1)
# Encoder
enc_embedding_layer = EmbeddingBlock(20000, D_MODEL)
enc_positional_encoding = PositionalEncoding(max_src_len, D_MODEL, 0.2)
## Pre Encoder part
enc_embeddings = enc_embedding_layer(input_tokens)
enc_pos_encoding_output = enc_positional_encoding(enc_embeddings)
## Encoder 
encoder = EncoderBlock(D_MODEL, H)
encoder_output = encoder(enc_pos_encoding_output, src_masking)


# Decoder
output_tokens = torch.Tensor([[231, 243, 981, 276, 32]]).to(torch.long)
output_tokens = nn.functional.pad(output_tokens, (0,max_tgt_len - output_tokens.shape[1]), mode='constant', value=1)
tgt_masking = output_tokens != 1
tgt_masking = tgt_masking.unsqueeze(1).unsqueeze(1)

causal_masking = torch.tril(torch.ones(max_tgt_len, max_tgt_len), diagonal=0).bool()
tgt_masking = tgt_masking & causal_masking

dec_embedding_layer = EmbeddingBlock(20000, D_MODEL)
dec_positional_encoding = PositionalEncoding(max_tgt_len, D_MODEL, 0.2)

dec_embeddings = dec_embedding_layer(output_tokens)
dec_pos_encoding_output = dec_positional_encoding(dec_embeddings)

decoder = DecoderBlock(D_MODEL, H)
decoder_output = decoder(dec_pos_encoding_output, encoder_output, src_masking, tgt_masking)

## Transformer

In [12]:
import torch
import torch.nn as nn
from Transformer import Transformer

D_MODEL = 512
H = 8
VOCAB_SIZE = 20000
MAX_LEN = 10
N_Enc = 10
N_Dec = 10

transformer = Transformer(D_MODEL, H, VOCAB_SIZE, MAX_LEN, N_Enc, N_Dec)

## Assuming padding token is 1
src_tokens = torch.Tensor([[32, 54, 285, 237, 483]]).to(torch.long)
src_tokens = nn.functional.pad(src_tokens, (0, 10 - src_tokens.shape[1]), mode='constant', value=1)
src_masking = src_tokens != 1
src_masking = src_masking.unsqueeze(1).unsqueeze(1)


tgt_tokens = torch.Tensor([[464, 643, 746, 56]]).to(torch.long)
tgt_tokens = nn.functional.pad(tgt_tokens, (0, 10 - tgt_tokens.shape[1]), mode='constant', value=1)

tgt_masking = tgt_tokens != 1
tgt_masking = tgt_masking.unsqueeze(1).unsqueeze(1)

causal_masking = torch.tril(torch.ones(10, 10), diagonal=0).bool()
tgt_masking = tgt_masking & causal_masking



transformer(src_tokens, tgt_tokens, src_masking, tgt_masking).shape

torch.Size([1, 10, 20000])

tensor([[[ 0.6125,  0.4123,  0.6564,  ..., -0.2702, -0.4311,  0.5068],
         [ 0.9454,  0.4401,  0.2980,  ..., -0.2119, -0.6527,  0.1723],
         [ 1.1203,  0.4115,  0.9785,  ...,  0.0476, -0.6120, -0.3311],
         ...,
         [ 0.3399,  0.2411,  0.3428,  ..., -0.1683, -0.6210, -0.0185],
         [ 0.2155, -0.1447,  0.4482,  ...,  0.1051, -0.4866,  0.1996],
         [ 0.3242, -0.0373,  0.4180,  ...,  0.0646, -0.4185,  0.3302]]],
       grad_fn=<ViewBackward0>)